# Generated by Django 2.1.4 on 2019-08-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuestionario',
            fields=[
                ('id_cuestionario', models.IntegerField(primary_key=True, serialize=False)),
                ('resultado_pregunta_cuestionario', models.IntegerField()),
                ('id_pregunta_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.preguntas_test_inteligencia')),
            ],
        ),
    ]
