# Generated by Django 2.1.1 on 2021-01-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_cuestionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.AutoField(primary_key=True, auto_created=True, serialize=False),
        ),
    ]
