# Generated by Django 2.1.1 on 2021-01-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20210102_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
