# Generated by Django 2.1.1 on 2021-01-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20210102_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
