# Generated by Django 2.1.1 on 2021-01-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20210102_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_cuenta',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
