# Generated by Django 2.1.1 on 2021-01-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20210102_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
